"""initial_schema

Revision ID: 8c3167adbb26
Revises: 
Create Date: 2026-06-06 01:16:29.471404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '8c3167adbb26'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trucks', schema=None) as batch_op:
        batch_op.alter_column('scheduled_off_days',
               existing_type=sqlite.JSON(),
               nullable=False,
               existing_server_default=sa.text("'[]'"))
        batch_op.create_index(batch_op.f('ix_trucks_qr_token'), ['qr_token'], unique=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('display_role',
               existing_type=sa.TEXT(),
               type_=sa.String(length=80),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('display_role',
               existing_type=sa.String(length=80),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('trucks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trucks_qr_token'))
        batch_op.alter_column('scheduled_off_days',
               existing_type=sqlite.JSON(),
               nullable=True,
               existing_server_default=sa.text("'[]'"))

    # ### end Alembic commands ###
